server:
  port: 8000

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-security-test?useUnicode=true&characterEncoding=utf8mb4
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root

zuul:
  ignoredServices: '/ignore/**'
  routes:
    zuulauth: /auth/**